package com.example.msscpizzaorder.domain;

public enum PizzaOrderStatus {

    NEW, VALIDATED, VALIDATION_EXCEPTION, VALIDATION_PENDING,
    ALLOCATION_PENDING, ALLOCATED, ALLOCATION_EXCEPTION,
    PENDING_INVENTORY, DELIVERED, PICKED_UP,
    DELIVERY_EXCEPTION, CANCELLED
}
